import {useLanguage} from './i18n';
import { useEffect, useState } from 'react';
import { api } from './api';
type Analysis = { width: number; height: number; hasAlpha: boolean; transparency: string; transparentPixels: number; partialPixels: number; bounds: { x: number; y: number; width: number; height: number; margins: { left: number; top: number; right: number; bottom: number } } | null; rules: { alphaThreshold: number; minimumRowCoverage: number; minimumColumnCoverage: number; backgrounds: { id: string; label: string; color: string }[] } };
export function ArtAnalysis({ clanKey, file, url }: { clanKey: string; file: string; url: string }) {
 const {t}=useLanguage();
  const [model, setModel] = useState<Analysis>(); const [error, setError] = useState(''); const [background, setBackground] = useState('dark');
  useEffect(() => { let active = true; setModel(undefined); setError(''); api<Analysis>(`/clans/${clanKey}/art-analysis?file=${encodeURIComponent(file)}`).then(m => { if (active) setModel(m); }).catch(e => { if (active) setError(e.message); }); return () => { active = false; }; }, [clanKey, file]);
  return <section><div className="head-actions">{model?.rules.backgrounds.map(b => <button key={b.id} className={background === b.id ? 'primary' : 'secondary'} onClick={() => setBackground(b.id)}>{t(b.label)}</button>)}</div><img src={url} alt={t("Recurso sobre el fondo seleccionado")} style={{ background: model?.rules.backgrounds.find(b => b.id === background)?.color }} />{error && <p role="alert">{t(error)}</p>}{model && <><p>{model.transparency === 'opaque' ? t("Imagen completamente opaca. Si este uso requiere recorte, revisa el fondo.") : t("Transparencia detectada: {v0} píxeles transparentes y {v1} semitransparentes.",{v0:model.transparentPixels,v1:model.partialPixels})}</p>{model.bounds ? <p>{t("Área visible:")}{" "}{model.bounds.width} × {model.bounds.height}{" "}{t("px. Márgenes: izquierda")}{" "}{model.bounds.margins.left}{t(", arriba")}{" "}{model.bounds.margins.top}{t(", derecha")}{" "}{model.bounds.margins.right}{t(", abajo")}{" "}{model.bounds.margins.bottom}.</p> : <p>{t("No se detecta un área visible con los umbrales configurados.")}</p>}<small>{t("Medición con alpha >")}{" "}{model.rules.alphaThreshold}{t(", filas con al menos")}{" "}{model.rules.minimumRowCoverage * 100}{t("% de cobertura y columnas con")}{" "}{model.rules.minimumColumnCoverage * 100}{t("%. Puede excluir detalles finos o brillos. Un fondo de cuadros o negro pintado necesita revisión visual. La medición no modifica el archivo ni ajusta el personaje.")}</small></>}</section>;
}
