import {useLanguage} from './i18n';
import { useEffect, useState } from 'react';
import { api } from './api';
type Row = { group: string; label: string; conditional: boolean; size: string; section: string; id: string; name: string; file: string; field: string; status: string; note: string; image?: string; width?: number; height?: number };
const labels: Record<string, string> = { ok: 'Archivo legible', undeclared: 'Sin declarar', external: 'Externo · revisión manual', unresolved: 'Sin resolver', missing: 'Falta archivo', 'case-mismatch': 'Mayúsculas distintas', 'invalid-path': 'Ruta o imagen inválida' };
export function ArtChecklist({ clanKey }: { clanKey: string }) {
 const {t}=useLanguage();
  const [rows, setRows] = useState<Row[]>([]); const [query, setQuery] = useState(''); const [group, setGroup] = useState('all'); const [status, setStatus] = useState('all'); const [error, setError] = useState(''); const [loaded, setLoaded] = useState(false);
  useEffect(() => { let active = true; setLoaded(false); setRows([]); setError(''); api<{ rows: Row[] }>(`/clans/${clanKey}/art-checklist`).then(m => { if (active) { setRows(m.rows); setLoaded(true); } }).catch(e => { if (active) setError(e.message); }); return () => { active = false; }; }, [clanKey]);
  const filtered = rows.filter(r => (group === 'all' || r.group === group) && (status === 'all' || r.status === status) && `${t(r.label)} ${r.name} ${r.id} ${r.file} ${r.field}`.toLocaleLowerCase().includes(query.toLocaleLowerCase()));
  return <details className="panel"><summary>{t("Checklist de arte del clan ·")}{" "}{rows.length}{" "}{t("usos revisados")}</summary><p>{t("Comprueba enlaces y archivos de los roles declarados. Las medidas son orientativas. Un archivo legible todavía requiere revisión visual; compartir imágenes entre usos es válido. Los roles sin declarar no son automáticamente errores ni requisitos del cargador.")}</p>{error && <p role="alert" className="notice error">{t(error)}</p>}{!loaded && !error && <p>{t("Cargando checklist…")}</p>}<div className="filters"><input aria-label={t("Buscar en checklist de arte")} placeholder={t("Recurso, objeto, campo o archivo…")} value={query} onChange={e => setQuery(e.target.value)} /><select aria-label={t("Grupo de arte")} value={group} onChange={e => setGroup(e.target.value)}><option value="all">{t("Todos los grupos")}</option>{[...new Set(rows.map(r => r.group))].map(g => <option key={g} value={g}>{t(g)}</option>)}</select><select aria-label={t("Estado del arte")} value={status} onChange={e => setStatus(e.target.value)}><option value="all">{t("Todos los estados")}</option>{Object.entries(labels).map(([id, label]) => <option key={id} value={id}>{t(label)}</option>)}</select><span>{filtered.length}{" "}{t("resultados")}</span></div><div className="table-panel"><table><thead><tr><th>{t("Uso / objeto")}</th><th>{t("Estado")}</th><th>{t("Medida actual / referencia")}</th></tr></thead><tbody>{filtered.map(r => <tr key={r.section + r.file + r.id + r.field}><td><strong>{t(r.label)}{r.conditional ? t(" · condicional") : ''}</strong><small>{r.name} · {t(r.group)}</small><small>{r.section} · {r.id} · {r.field}</small><small>{r.file}</small></td><td>{t(labels[r.status] ?? r.status)}<small>{t(r.note)}</small>{r.image && <small>{r.image}</small>}</td><td>{r.width && r.height ? `${r.width} × ${r.height}` : '—'}<small>{t(r.size)}</small></td></tr>)}</tbody></table></div>{loaded && !filtered.length && <p>{t("No hay usos que coincidan con estos filtros.")}</p>}<small>{t("El checklist sigue los roles de config/art-checklist.json. La asociación completa de estilos de clase, bundles, recursos de reliquias/equipos/salas y usos textuales se ampliará en siguientes incrementos.")}</small></details>;
}
