import {useLanguage} from './i18n';
import React,{useEffect,useState} from 'react';
import {api,post} from './api';
import type {ClanSnapshot,Entry,FieldRule} from './types';
type Preview={changed:boolean;token:string;changes:{id:string;before:unknown;after:unknown}[]};
export function DeleteDefinition({clan,entry,onSaved}:{clan:ClanSnapshot;entry:Entry;onSaved:()=>void}){
 const {t}=useLanguage();
 const [allowed,setAllowed]=useState<string[]>([]);const [preview,setPreview]=useState<Preview>();const [error,setError]=useState('');const [busy,setBusy]=useState(false);
 useEffect(()=>{setPreview(undefined);setError('');api<{deleteSections:string[]}>('/content-actions').then(v=>setAllowed(v.deleteSections)).catch(e=>setError(e.message));},[entry.id,entry.hash]);
 if(!allowed.includes(entry.section))return null;
 async function act(save:boolean){setBusy(true);setError('');try{const request={operation:'delete',section:entry.section,targets:[{id:entry.id,file:entry.file,expectedHash:entry.hash}],expectedToken:save?preview?.token:undefined};if(save){await post(`/clans/${clan.key}/content-actions/save`,request);setPreview(undefined);onSaved();}else setPreview(await post<Preview>(`/clans/${clan.key}/content-actions/preview`,request));}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <details className="edit-box"><summary>{t("Retirar definición")}</summary><p>{t("Se retira solo este objeto del JSON con respaldo. No se borran imágenes ni dependencias. Se bloquea si se detectan referencias desde otros objetos o fuentes C#.")}</p>{error&&<p role="alert" className="notice error">{t(error)}</p>}<button disabled={busy} onClick={()=>act(false)}>{t("Revisar retirada")}</button>{preview&&<div className="preview"><p>{t("Retirar {id} de {file}. Los usos calculados desde código o archivos externos necesitan revisión manual.",{id:entry.id,file:entry.file})}</p><button disabled={busy||!preview.changed} onClick={()=>act(true)}>{t("Retirar definición con respaldo")}</button></div>}</details>;
}
export function BatchFields({clan,onSaved}:{clan:ClanSnapshot;onSaved:()=>void}){
 const {t}=useLanguage();
 const [sections,setSections]=useState<{id:string;label:string;fields:FieldRule[]}[]>([]);const [section,setSection]=useState('cards');const [field,setField]=useState('cost');const [selected,setSelected]=useState<string[]>([]);const [query,setQuery]=useState('');const [value,setValue]=useState('');const [preview,setPreview]=useState<Preview>();const [busy,setBusy]=useState(false);const [error,setError]=useState('');
 useEffect(()=>{api<{batchSections:typeof sections}>('/content-actions').then(v=>setSections(v.batchSections)).catch(e=>setError(e.message));},[]);
 const fields=sections.find(s=>s.id===section)?.fields??[];const rule=fields.find(f=>f.path===field);const choices=clan.entries.filter(e=>e.section===section);const visible=choices.filter(e=>`${e.name} ${e.id} ${e.file} ${e.data.rarity??''} ${e.data.card_type??''}`.toLowerCase().includes(query.toLowerCase()));
 async function act(save:boolean){setBusy(true);setError('');try{const parsed=rule?.type==='number'?Number(value):value;if(value==='')throw Error(t('Introduce el valor.'));const request={operation:'batch',section,field,value:parsed,targets:choices.filter(e=>selected.includes(e.id)).map(e=>({id:e.id,file:e.file,expectedHash:e.hash})),expectedToken:save?preview?.token:undefined};if(save){await post(`/clans/${clan.key}/content-actions/save`,request);setPreview(undefined);setSelected([]);onSaved();}else setPreview(await post<Preview>(`/clans/${clan.key}/content-actions/preview`,request));}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <details className="panel content-panel"><summary>{t("Editar campos de varias cartas o unidades")}</summary><fieldset disabled={busy}><label>{t("Contenido")}<select value={section} onChange={e=>{setSection(e.target.value);setField(sections.find(s=>s.id===e.target.value)?.fields[0]?.path??'');setSelected([]);setPreview(undefined);}}>{sections.map(s=><option key={s.id} value={s.id}>{t(s.label)}</option>)}</select></label><label>{t("Campo")}<select value={field} onChange={e=>{setField(e.target.value);setValue('');setPreview(undefined);}}>{fields.map(f=><option key={f.path} value={f.path}>{t(f.label)}</option>)}</select></label><label>{t("Nuevo valor")} {rule?.type==='select'?<select value={value} onChange={e=>{setValue(e.target.value);setPreview(undefined);}}><option value="">{t("Selecciona…")}</option>{rule.options?.map(o=><option key={o} value={o}>{o}</option>)}</select>:<input type="number" value={value} onChange={e=>{setValue(e.target.value);setPreview(undefined);}}/>}</label><label>{t("Buscar nombre, ID, rareza o tipo")}<input value={query} onChange={e=>setQuery(e.target.value)}/></label><p>{t("{count} seleccionados. Filtrar conserva la selección.",{count:selected.length})}</p><div className="scroll-list">{visible.map(e=><label key={e.file+e.id}><input type="checkbox" checked={selected.includes(e.id)} onChange={ev=>{setSelected(v=>ev.target.checked?[...v,e.id]:v.filter(id=>id!==e.id));setPreview(undefined);}}/>{e.name} · {e.id}</label>)}</div><button disabled={!selected.length} onClick={()=>act(false)}>{t("Previsualizar lote")}</button><button onClick={()=>{setSelected([]);setPreview(undefined);}}>{t("Descartar selección")}</button>{error&&<p role="alert">{t(error)}</p>}{preview&&<div className="preview">{preview.changes.map(c=><p key={c.id}>{c.id}: {JSON.stringify(c.before)} → {JSON.stringify(c.after)}</p>)}<button disabled={!preview.changed} onClick={()=>act(true)}>{t("Guardar lote con respaldo")}</button></div>}</fieldset></details>;
}
