import {useLanguage} from './i18n';
import {indexedLabel} from './i18n-core';
import React,{useEffect,useState} from 'react';
import {api,post} from './api';
import type {ClanSnapshot,Entry} from './types';
type Slot={field:string;label:string;mode:'single'|'list';help:string;external?:boolean;current:unknown;candidates:{id:string;name:string}[];uses:{id:string;name:string;section:string}[]};
type Preview={changed:boolean;before:unknown;after:unknown;token:string;uses:Slot['uses']};
export function ReferenceEditor({clan,entry,onSaved}:{clan:ClanSnapshot;entry:Entry;onSaved:()=>void}){
 const {t}=useLanguage();
 const [slots,setSlots]=useState<Slot[]>([]);const [field,setField]=useState('');const [target,setTarget]=useState('');const [query,setQuery]=useState('');const [external,setExternal]=useState(false);const [externalId,setExternalId]=useState('');const [mod,setMod]=useState('');
 const [intent,setIntent]=useState<Record<string,unknown>>();const [preview,setPreview]=useState<Preview>();const [error,setError]=useState('');const [busy,setBusy]=useState(false);
 useEffect(()=>{let active=true;setSlots([]);setField('');setIntent(undefined);setPreview(undefined);setError('');setTarget('');setQuery('');setExternal(false);setExternalId('');setMod('');api<Slot[]>(`/clans/${clan.key}/references?section=${encodeURIComponent(entry.section)}&id=${encodeURIComponent(entry.id)}&file=${encodeURIComponent(entry.file)}`).then(v=>{if(active){setSlots(v);setField(v[0]?.field??'');}}).catch(e=>{if(active)setError(e.message);});return()=>{active=false;};},[clan.key,entry.section,entry.id,entry.file,entry.hash]);
 const slot=slots.find(s=>s.field===field);if(!slot&&!error)return null;
 async function prepare(operation:string,index?:number){setBusy(true);setError('');setPreview(undefined);const input={section:entry.section,id:entry.id,file:entry.file,field,expectedHash:entry.hash,operation,index,...(['set','append'].includes(operation)?external?{external:{id:externalId,...(mod?{mod_reference:mod}:{})}}:{targetId:target}:{})};try{setPreview(await post<Preview>(`/clans/${clan.key}/references/preview`,input));setIntent(input);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function save(){setBusy(true);setError('');try{await post(`/clans/${clan.key}/references/save`,{...intent,expectedToken:preview?.token});setPreview(undefined);onSaved();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <details className="edit-box"><summary>{t("Conexiones y orden de referencias")}</summary>{error&&<p className="notice error" role="alert">{t(error)}</p>}{slot&&<fieldset disabled={busy}><label>{t("Conexión")}<select value={field} onChange={e=>{setField(e.target.value);setPreview(undefined);setTarget('');}}>{slots.map(s=><option key={s.field} value={s.field}>{indexedLabel(s.label,t)}</option>)}</select></label><p>{t(slot.help)}</p><small>{slot.field}</small>{slot.mode==='list'&&Array.isArray(slot.current)?slot.current.map((v,i)=><div key={i}><code>{JSON.stringify(v)}</code><div className="head-actions"><button aria-label={t("Subir referencia {index}",{index:i+1})} disabled={!i} onClick={()=>prepare('up',i)}>↑</button><button aria-label={t("Bajar referencia {index}",{index:i+1})} disabled={i=== (slot.current as unknown[]).length-1} onClick={()=>prepare('down',i)}>↓</button><button aria-label={t("Quitar referencia {index}",{index:i+1})} onClick={()=>prepare('remove',i)}>{t("Quitar")}</button></div></div>):<p>{t("Actual:")} {JSON.stringify(slot.current??t('Sin declarar'))}</p>}{slot.external&&<label><input type="checkbox" checked={external} onChange={e=>{setExternal(e.target.checked);setPreview(undefined);}}/>{t("Usar referencia externa o del juego")}</label>}{external?<><label>{t("ID / nombre del recurso")}<input value={externalId} onChange={e=>{setExternalId(e.target.value);setPreview(undefined);}}/></label><label>{t("mod_reference (vacío para juego base)")}<input value={mod} onChange={e=>{setMod(e.target.value);setPreview(undefined);}}/></label><p>{t("Requiere que el recurso exista y esté disponible en partida. No se valida su código ni se instala la dependencia.")}</p></>:<><label>{t("Buscar definición")}<input value={query} onChange={e=>setQuery(e.target.value)}/></label><label>{t("Definición local")}<select value={target} onChange={e=>{setTarget(e.target.value);setPreview(undefined);}}><option value="">{t("Selecciona…")}</option>{slot.candidates.filter(c=>c.id===target||`${c.name} ${c.id}`.toLowerCase().includes(query.toLowerCase())).map(c=><option key={c.id} value={c.id}>{c.name} · {c.id}</option>)}</select></label></>}<button disabled={external?!externalId.trim():!target} onClick={()=>prepare(slot.mode==='list'?'append':'set')}>{t(slot.mode==='list'?'Previsualizar alta':'Previsualizar sustitución')}</button>{preview&&<div className="preview"><p>{JSON.stringify(preview.before??t('Sin declarar'))} → {JSON.stringify(preview.after)}</p><p>{t("{count} objetos referencian este objeto. El cambio puede afectar a todos sus usuarios.",{count:preview.uses.length})}</p><button disabled={!preview.changed} onClick={save}>{t("Guardar conexión con respaldo")}</button></div>}</fieldset>}</details>;
}
